# Generated by Django 4.2.7 on 2026-01-19 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lectures", "0002_lecture_transcript_approved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("ai_generated_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("study_count", models.PositiveIntegerField(default=0)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_sets",
                        to="schools.classroom",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_sets",
                        to="lectures.lecture",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_flashcard_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard Set",
                "verbose_name_plural": "Flashcard Sets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(help_text="Front of the card")),
                ("answer", models.TextField(help_text="Back of the card")),
                ("hint", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_ai_generated", models.BooleanField(default=False)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="flashcards.flashcardset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentFlashcardSetView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Time spent studying in seconds"
                    ),
                ),
                ("cards_studied", models.PositiveIntegerField(default=0)),
                (
                    "flashcard_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_views",
                        to="flashcards.flashcardset",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_set_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Flashcard Set View",
                "verbose_name_plural": "Student Flashcard Set Views",
                "unique_together": {("flashcard_set", "student")},
            },
        ),
        migrations.CreateModel(
            name="StudentFlashcardProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("not_studied", "Not Studied"),
                            ("hard", "Hard"),
                            ("medium", "Medium"),
                            ("easy", "Easy"),
                            ("mastered", "Mastered"),
                        ],
                        default="not_studied",
                        max_length=20,
                    ),
                ),
                ("times_studied", models.PositiveIntegerField(default=0)),
                ("times_correct", models.PositiveIntegerField(default=0)),
                ("times_incorrect", models.PositiveIntegerField(default=0)),
                ("last_studied_at", models.DateTimeField(blank=True, null=True)),
                ("next_review_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="flashcards.flashcard",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Flashcard Progress",
                "verbose_name_plural": "Student Flashcard Progress",
                "unique_together": {("flashcard", "student")},
            },
        ),
        migrations.AddIndex(
            model_name="flashcardset",
            index=models.Index(
                fields=["classroom", "-published_at"],
                name="flashcards__classro_8337ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flashcardset",
            index=models.Index(
                fields=["teacher", "-created_at"], name="flashcards__teacher_74e775_idx"
            ),
        ),
    ]
