# Generated by Django 4.2.7 on 2026-02-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={
                "ordering": ["grade", "section"],
                "verbose_name": "Classroom",
                "verbose_name_plural": "Classrooms",
            },
        ),
    ]
