# Generated by Django 4.2.7 on 2026-02-05 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_transcript_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('overall_feedback', models.TextField(blank=True)),
                ('teacher_comments', models.TextField(blank=True)),
                ('ai_suggested_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_grading_data', models.JSONField(default=dict, help_text='Detailed AI analysis and scoring breakdown')),
                ('ai_grading_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('ai_grading_tokens', models.IntegerField(default=0)),
                ('teacher_modified_ai_score', models.BooleanField(default=False, help_text='True if teacher changed AI suggestion')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assignment Grade',
                'verbose_name_plural': 'Assignment Grades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('expected_answer_keywords', models.JSONField(blank=True, default=list, help_text='Keywords AI should look for when grading')),
                ('expected_answer_length', models.CharField(blank=True, help_text='e.g., "2-3 sentences", "1 paragraph"', max_length=50)),
                ('grading_notes', models.TextField(blank=True, help_text='Criteria for full marks')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for equal distribution', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assignment Question',
                'verbose_name_plural': 'Assignment Questions',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='GradingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ai_graded', 'AI Graded'), ('teacher_reviewed', 'Teacher Reviewed'), ('score_modified', 'Score Modified'), ('feedback_added', 'Feedback Added'), ('published', 'Published to Student')], max_length=20)),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grading Audit Log',
                'verbose_name_plural': 'Grading Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion_name', models.CharField(help_text='e.g., Content Accuracy, Grammar, Structure', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight_percentage', models.PositiveIntegerField(help_text='Percentage weight (all criteria must sum to 100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rubric Criterion',
                'verbose_name_plural': 'Rubric Criteria',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RubricScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ai_suggested_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rubric Score',
                'verbose_name_plural': 'Rubric Scores',
            },
        ),
        migrations.RemoveField(
            model_name='assignmentattachment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submissionfile',
            name='submission',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Assignment Submission', 'verbose_name_plural': 'Assignment Submissions'},
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='assignments_classro_3e8430_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='assignments_teacher_764703_idx',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='late_penalty_percentage',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='linked_lecture_note',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='ai_confidence_score',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='is_ai_graded',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='points_earned',
        ),
        migrations.AddField(
            model_name='assignment',
            name='ai_generation_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cost in USD', max_digits=8),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ai_generation_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_format',
            field=models.CharField(choices=[('essay', 'Essay/Long Answer'), ('short_answer', 'Short Answer Questions'), ('case_study', 'Case Study Analysis')], default='short_answer', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='generation_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grading_method',
            field=models.CharField(choices=[('manual', 'Manual Grading'), ('ai_assisted', 'AI-Assisted (Teacher Reviews)'), ('automated', 'Fully Automated AI')], default='ai_assisted', max_length=15),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grading_type',
            field=models.CharField(choices=[('basic', 'Basic (Overall Score)'), ('rubric', 'Rubric-Based (Criteria)')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='late_penalty_per_day',
            field=models.PositiveIntegerField(default=10, help_text='Percentage penalty per day late', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='pass_marks',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='assignment',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='source_lecture',
            field=models.ForeignKey(blank=True, help_text='If AI-generated, the lecture it was based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assignments', to='lectures.lecture'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('online', 'Online (Type Answer)'), ('offline', 'Offline (Upload PDF)')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='answers',
            field=models.JSONField(default=dict, help_text='For online: {question_id: answer_text}. For offline: metadata.'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='days_late',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='PDF file for offline submissions (max 5MB)', null=True, upload_to='assignments/submissions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('grading', 'Being Graded'), ('graded', 'Graded'), ('returned', 'Returned to Student')], db_index=True, default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['classroom', 'is_published'], name='assignments_classro_803e92_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_7a9bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by', '-created_at'], name='assignments_created_636db3_idx'),
        ),
        migrations.DeleteModel(
            name='AssignmentAttachment',
        ),
        migrations.DeleteModel(
            name='SubmissionFile',
        ),
        migrations.AddField(
            model_name='rubricscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='rubricscore',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='assignments.assignmentgrade'),
        ),
        migrations.AddField(
            model_name='rubriccriterion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='gradingauditlog',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='assignments.assignmentgrade'),
        ),
        migrations.AddField(
            model_name='gradingauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignments.assignmentsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='rubricscore',
            unique_together={('grade', 'criterion')},
        ),
        migrations.AddIndex(
            model_name='gradingauditlog',
            index=models.Index(fields=['grade', '-timestamp'], name='assignments_grade_i_0ce346_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentquestion',
            unique_together={('assignment', 'question_number')},
        ),
    ]
