# Generated by Django 4.2.7 on 2026-02-06 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assignments",
            "0002_assignmentgrade_assignmentquestion_gradingauditlog_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="submission_method",
            field=models.CharField(
                blank=True,
                choices=[("text", "Text Entry"), ("pdf", "PDF Upload")],
                help_text="For online assignments: how student submitted (text vs PDF)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="answers",
            field=models.JSONField(
                default=dict,
                help_text="For text: {question_id: answer_text}. For PDF: {metadata: {...}}",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                help_text="PDF file for both online-PDF and offline submissions",
                null=True,
                upload_to="assignments/submissions/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
