# Generated by Django 6.0.1 on 2026-01-14 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('attendance', 'Attendance'), ('behavior', 'Behavior'), ('participation', 'Participation'), ('special', 'Special')], db_index=True, max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('requirement_description', models.TextField(help_text='What student needs to do to earn this')),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('icon', models.CharField(default='trophy', help_text='Icon name/class', max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text='Hex color code', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False, help_text='Hidden until earned')),
                ('times_earned', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirement_type', models.CharField(choices=[('xp_milestone', 'XP Milestone'), ('level_reached', 'Level Reached'), ('badges_collected', 'Badges Collected'), ('streak_milestone', 'Streak Milestone'), ('perfect_scores', 'Perfect Scores'), ('custom', 'Custom')], max_length=30)),
                ('requirement_value', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('icon', models.CharField(default='star', max_length=50)),
                ('color', models.CharField(default='#FFA500', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.badge')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('leaderboard_type', models.CharField(choices=[('xp', 'Total XP'), ('level', 'Level'), ('badges', 'Badges Earned'), ('streak', 'Current Streak'), ('custom', 'Custom Metric')], max_length=20)),
                ('scope', models.CharField(choices=[('school', 'School-Wide'), ('classroom', 'Classroom'), ('grade', 'Grade Level')], max_length=20)),
                ('time_period', models.CharField(choices=[('all_time', 'All Time'), ('monthly', 'This Month'), ('weekly', 'This Week'), ('daily', 'Today')], default='all_time', max_length=20)),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_entries', models.PositiveIntegerField(default=10, help_text='Top N students to show')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='schools.classroom')),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentXP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_xp', models.PositiveIntegerField(db_index=True, default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('xp_to_next_level', models.PositiveIntegerField(default=100)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Consecutive days active')),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_badges_earned', models.PositiveIntegerField(default=0)),
                ('total_achievements', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student XP',
                'verbose_name_plural': 'Student XP',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('score', models.PositiveIntegerField(help_text='XP, badges count, etc.')),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(default=0, help_text='Positive = moved up, negative = moved down')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='gamification.leaderboard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['leaderboard', 'rank'],
                'indexes': [models.Index(fields=['leaderboard', 'rank'], name='gamificatio_leaderb_b02db0_idx')],
                'unique_together': {('leaderboard', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='gamification.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Achievement',
                'verbose_name_plural': 'Student Achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('student', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('earned_for', models.CharField(blank=True, help_text='What action earned this badge', max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('is_displayed', models.BooleanField(default=True, help_text='Show on student profile')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='gamification.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Badge',
                'verbose_name_plural': 'Student Badges',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['student', '-earned_at'], name='gamificatio_student_3ed7a4_idx')],
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('bonus', 'Bonus'), ('penalty', 'Penalty')], max_length=20)),
                ('source', models.CharField(choices=[('assignment_completed', 'Assignment Completed'), ('quiz_completed', 'Quiz Completed'), ('perfect_score', 'Perfect Score'), ('attendance', 'Attendance'), ('behavior', 'Good Behavior'), ('streak', 'Streak Bonus'), ('badge_earned', 'Badge Earned'), ('manual', 'Manual Award')], max_length=30)),
                ('amount', models.IntegerField(help_text='Positive for earned, negative for spent')),
                ('balance_after', models.PositiveIntegerField(help_text='Total XP after transaction')),
                ('description', models.CharField(max_length=255)),
                ('reference_type', models.CharField(blank=True, help_text='assignment, quiz, etc.', max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_xp', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Transaction',
                'verbose_name_plural': 'XP Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='gamificatio_student_41627e_idx')],
            },
        ),
    ]
