# Generated by Django 6.0.1 on 2026-01-14 18:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Template content in HTML/Markdown')),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note Template',
                'verbose_name_plural': 'Note Templates',
            },
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Rich text content')),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('auto_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notes/pdfs/%Y/%m/%d/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_notes', to='schools.classroom')),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.lecture')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.notetemplate')),
            ],
            options={
                'verbose_name': 'Lecture Note',
                'verbose_name_plural': 'Lecture Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNoteBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='notes.lecturenote')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Note Bookmark',
                'verbose_name_plural': 'Student Note Bookmarks',
            },
        ),
        migrations.CreateModel(
            name='StudentNoteView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent reading in seconds')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_views', to='notes.lecturenote')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Note View',
                'verbose_name_plural': 'Student Note Views',
            },
        ),
        migrations.CreateModel(
            name='StudentPersonalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('highlighted_text', models.TextField(blank=True)),
                ('position', models.JSONField(blank=True, help_text='Position in the document', null=True)),
                ('lecture_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='notes.lecturenote')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Personal Note',
                'verbose_name_plural': 'Student Personal Notes',
            },
        ),
        migrations.AddIndex(
            model_name='lecturenote',
            index=models.Index(fields=['classroom', '-published_at'], name='notes_lectu_classro_ae3bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturenote',
            index=models.Index(fields=['teacher', '-created_at'], name='notes_lectu_teacher_fa7819_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentnotebookmark',
            unique_together={('note', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentnoteview',
            unique_together={('note', 'student')},
        ),
    ]
