# Generated by Django 4.2.7 on 2026-01-22 08:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('lectures', '0002_lecture_transcript_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('final_score', models.PositiveIntegerField(default=0)),
                ('max_possible_score', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time taken in seconds')),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('max_combo_achieved', models.PositiveIntegerField(default=0)),
                ('lives_remaining', models.PositiveIntegerField(default=0)),
                ('detailed_results', models.JSONField(default=dict, help_text='Question-by-question breakdown')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Advanced performance metrics')),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('rank_achieved', models.PositiveIntegerField(blank=True, help_text='Position in leaderboard', null=True)),
            ],
            options={
                'verbose_name': 'Game Attempt',
                'verbose_name_plural': 'Game Attempts',
                'ordering': ['-completed_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon class', max_length=50)),
                ('game_type', models.CharField(choices=[('REACTION', 'Reaction Game'), ('PUZZLE', 'Puzzle Game'), ('MEMORY', 'Memory Game'), ('QUIZ', 'Quiz Game')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('min_questions', models.PositiveIntegerField(default=5)),
                ('max_questions', models.PositiveIntegerField(default=20)),
                ('default_time_per_question', models.PositiveIntegerField(default=8, help_text='Default time limit in seconds')),
                ('supports_difficulty', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Game Template',
                'verbose_name_plural': 'Game Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LectureGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=10)),
                ('question_count', models.PositiveIntegerField()),
                ('game_data', models.JSONField(help_text='Stores all game content (questions, config, etc.)')),
                ('estimated_duration', models.PositiveIntegerField(default=5, help_text='Estimated duration in minutes')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model_used', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('ai_generation_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_completion_time', models.PositiveIntegerField(default=0, help_text='Average completion time in seconds')),
                ('highest_score', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='schools.classroom')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_games', to=settings.AUTH_USER_MODEL)),
                ('highest_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_scores', to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='lectures.lecture')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_games', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='games.gametemplate')),
            ],
            options={
                'verbose_name': 'Lecture Game',
                'verbose_name_plural': 'Lecture Games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('last_played', models.DateTimeField()),
                ('best_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_entries', to='games.gameattempt')),
                ('lecture_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='games.lecturegame')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Leaderboard Entry',
                'verbose_name_plural': 'Game Leaderboard Entries',
                'ordering': ['lecture_game', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='lecture_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.lecturegame'),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lecturegame',
            index=models.Index(fields=['lecture', 'template'], name='games_lectu_lecture_4d4e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturegame',
            index=models.Index(fields=['is_published', '-created_at'], name='games_lectu_is_publ_b66085_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturegame',
            index=models.Index(fields=['difficulty'], name='games_lectu_difficu_cbcbae_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturegame',
            index=models.Index(fields=['classroom', '-created_at'], name='games_lectu_classro_7e8044_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturegame',
            unique_together={('lecture', 'template', 'difficulty')},
        ),
        migrations.AddIndex(
            model_name='gameleaderboard',
            index=models.Index(fields=['lecture_game', 'rank'], name='games_gamel_lecture_507db5_idx'),
        ),
        migrations.AddIndex(
            model_name='gameleaderboard',
            index=models.Index(fields=['lecture_game', '-best_score'], name='games_gamel_lecture_5c5568_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameleaderboard',
            unique_together={('lecture_game', 'student')},
        ),
        migrations.AddIndex(
            model_name='gameattempt',
            index=models.Index(fields=['student', 'lecture_game'], name='games_gamea_student_d37f26_idx'),
        ),
        migrations.AddIndex(
            model_name='gameattempt',
            index=models.Index(fields=['is_completed', '-completed_at'], name='games_gamea_is_comp_ee7cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='gameattempt',
            index=models.Index(fields=['lecture_game', '-final_score'], name='games_gamea_lecture_6f5eef_idx'),
        ),
    ]
