# Generated by Django 6.0.1 on 2026-01-13 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('chapter', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('recording_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lectures/audio/%Y/%m/%d/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lectures/video/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lectures/thumbnails/%Y/%m/%d/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('transcript', models.TextField(blank=True)),
                ('has_auto_generated_transcript', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(db_index=True, default=False)),
                ('is_shared_with_students', models.BooleanField(db_index=True, default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('notify_students', models.BooleanField(default=True)),
                ('notify_parents', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='schools.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.PositiveIntegerField(help_text='Timestamp in seconds')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='lectures.lecture')),
            ],
            options={
                'verbose_name': 'Lecture Bookmark',
                'verbose_name_plural': 'Lecture Bookmarks',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LectureResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lectures/resources/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lectures.lecture')),
            ],
            options={
                'verbose_name': 'Lecture Resource',
                'verbose_name_plural': 'Lecture Resources',
            },
        ),
        migrations.CreateModel(
            name='LectureView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Last watched position in seconds')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('watch_time', models.PositiveIntegerField(default=0, help_text='Total watch time in seconds')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='lectures.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture View',
                'verbose_name_plural': 'Lecture Views',
            },
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['classroom', '-created_at'], name='lectures_le_classro_f64e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['teacher', '-created_at'], name='lectures_le_teacher_0836b5_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['status', 'is_shared_with_students'], name='lectures_le_status_3a6deb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lectureview',
            unique_together={('lecture', 'student')},
        ),
    ]
