# Generated by Django 4.2.7 on 2026-01-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='transcript_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='transcript_approved_by_teacher',
            field=models.BooleanField(default=False, help_text='Teacher must approve transcript before AI features (notes, flashcards, quizzes) can use it'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='transcript_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=20),
        ),
    ]
