# Generated by Django 6.0.1 on 2026-01-14 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('incident_type', models.CharField(choices=[('disruption', 'Class Disruption'), ('disrespect', 'Disrespectful Behavior'), ('tardiness', 'Tardiness'), ('incomplete_work', 'Incomplete Work'), ('cheating', 'Academic Dishonesty'), ('bullying', 'Bullying'), ('other', 'Other')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('critical', 'Critical')], db_index=True, default='minor', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_lecture', 'AI - Lecture Analysis'), ('ai_behavior', 'AI - Behavior Detection'), ('system', 'System Generated')], db_index=True, default='manual', help_text='How this incident was created', max_length=20)),
                ('is_ai_generated', models.BooleanField(db_index=True, default=False)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence (0-100) if AI-generated', max_digits=5, null=True)),
                ('ai_transcript_snippet', models.TextField(blank=True, help_text='Transcript excerpt that triggered AI detection')),
                ('lecture_timestamp', models.PositiveIntegerField(blank=True, help_text='Timestamp in lecture (seconds) where incident occurred', null=True)),
                ('student_notified', models.BooleanField(default=False)),
                ('student_notified_at', models.DateTimeField(blank=True, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_notes', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_incidents', to='schools.classroom')),
                ('lecture', models.ForeignKey(blank=True, help_text='Lecture where incident occurred (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_incidents', to='lectures.lecture')),
                ('reported_by', models.ForeignKey(blank=True, help_text='Teacher/Admin who reported (null if AI-generated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavior Incident',
                'verbose_name_plural': 'Behavior Incidents',
                'ordering': ['-incident_date'],
                'indexes': [models.Index(fields=['student', '-incident_date'], name='behavior_be_student_0a5920_idx'), models.Index(fields=['classroom', '-incident_date'], name='behavior_be_classro_53e228_idx'), models.Index(fields=['is_ai_generated', '-incident_date'], name='behavior_be_is_ai_g_077e89_idx'), models.Index(fields=['severity', '-incident_date'], name='behavior_be_severit_efe4fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note_type', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, default='neutral', max_length=20)),
                ('note', models.TextField()),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_lecture', 'AI - Lecture Analysis'), ('system', 'System Generated')], default='manual', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_transcript_snippet', models.TextField(blank=True)),
                ('lecture_timestamp', models.PositiveIntegerField(blank=True, null=True)),
                ('visible_to_student', models.BooleanField(default=True)),
                ('visible_to_parent', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_notes', to='schools.classroom')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_notes', to='lectures.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_notes', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_behavior_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavior Note',
                'verbose_name_plural': 'Behavior Notes',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', '-date'], name='behavior_be_student_7ef14f_idx'), models.Index(fields=['note_type', '-date'], name='behavior_be_note_ty_a6ac33_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minor_incidents', models.PositiveIntegerField(default=0)),
                ('moderate_incidents', models.PositiveIntegerField(default=0)),
                ('serious_incidents', models.PositiveIntegerField(default=0)),
                ('critical_incidents', models.PositiveIntegerField(default=0)),
                ('total_incidents', models.PositiveIntegerField(default=0)),
                ('ai_generated_incidents', models.PositiveIntegerField(default=0)),
                ('manual_incidents', models.PositiveIntegerField(default=0)),
                ('positive_notes', models.PositiveIntegerField(default=0)),
                ('neutral_notes', models.PositiveIntegerField(default=0)),
                ('negative_notes', models.PositiveIntegerField(default=0)),
                ('total_notes', models.PositiveIntegerField(default=0)),
                ('behavior_score', models.DecimalField(decimal_places=2, default=100, help_text='100 = perfect, decreases with incidents', max_digits=5)),
                ('last_incident_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_behavior_stats', to='schools.classroom')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavior Statistics',
                'verbose_name_plural': 'Behavior Statistics',
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
