# Generated by Django 4.2.7 on 2026-01-15 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lectures", "0002_lecture_transcript_approved_at_and_more"),
        ("behavior", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingBehaviorDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_name",
                    models.CharField(
                        help_text="Student name extracted from transcript",
                        max_length=200,
                    ),
                ),
                ("behavior_type", models.CharField(max_length=20)),
                ("severity", models.CharField(max_length=20)),
                (
                    "description",
                    models.TextField(help_text="AI-generated neutral description"),
                ),
                (
                    "original_statement",
                    models.TextField(help_text="Exact quote from lecture transcript"),
                ),
                ("is_positive", models.BooleanField(default=False)),
                ("ai_confidence", models.CharField(default="MEDIUM", max_length=20)),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=75.0,
                        help_text="AI confidence (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "detection_sensitivity",
                    models.CharField(
                        default="MEDIUM",
                        help_text="Sensitivity level used for detection",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved & Processed"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified & Processed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "teacher_notes",
                    models.TextField(
                        blank=True, help_text="Teacher comments or modifications"
                    ),
                ),
                ("modified_description", models.TextField(blank=True)),
                ("modified_severity", models.CharField(blank=True, max_length=20)),
                ("modified_behavior_type", models.CharField(blank=True, max_length=20)),
                ("student_notified", models.BooleanField(default=False)),
                ("parent_notified", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_detection",
                        to="behavior.behaviorincident",
                    ),
                ),
                (
                    "created_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_detection",
                        to="behavior.behaviornote",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_behavior_detections",
                        to="lectures.lecture",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_behavior_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Behavior Detection",
                "verbose_name_plural": "Pending Behavior Detections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lecture", "-created_at"],
                        name="behavior_pe_lecture_0bb9a7_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="behavior_pe_status_b19c83_idx",
                    ),
                    models.Index(
                        fields=["is_positive", "-created_at"],
                        name="behavior_pe_is_posi_385d6e_idx",
                    ),
                ],
            },
        ),
    ]
