# Generated by Django 4.2.7 on 2026-01-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_pendingbehaviordetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingbehaviordetection',
            name='modified_behavior_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pendingbehaviordetection',
            name='modified_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendingbehaviordetection',
            name='modified_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pendingbehaviordetection',
            name='teacher_notes',
            field=models.TextField(blank=True, help_text='Teacher comments or modifications', null=True),
        ),
    ]
