# Generated by Django 6.0.1 on 2026-01-14 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(choices=[('grades', 'Grades Export'), ('attendance', 'Attendance Export'), ('students', 'Students Export'), ('assignments', 'Assignments Export'), ('quizzes', 'Quizzes Export'), ('behavior', 'Behavior Export'), ('resources', 'Resources Export'), ('custom', 'Custom Export')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('filters', models.JSONField(default=dict, help_text='Filters: classroom, date_range, students, etc.')),
                ('file_format', models.CharField(choices=[('excel', 'Excel (.xlsx)'), ('csv', 'CSV')], default='excel', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0, help_text='Number of rows exported')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export',
                'verbose_name_plural': 'Data Exports',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('student_report_card', 'Student Report Card'), ('progress_report', 'Progress Report'), ('attendance_report', 'Attendance Report'), ('behavior_report', 'Behavior Report'), ('transcript', 'Academic Transcript'), ('class_performance', 'Class Performance'), ('parent_summary', 'Parent Summary'), ('custom', 'Custom Report')], db_index=True, max_length=30)),
                ('sections', models.JSONField(default=dict, help_text='Sections to include: grades, attendance, behavior, etc.')),
                ('layout_config', models.JSONField(default=dict, help_text='Layout settings: colors, fonts, logo, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('next_run_date', models.DateTimeField(db_index=True)),
                ('last_run_date', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send report to')),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='schools.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('student_report_card', 'Student Report Card'), ('progress_report', 'Progress Report'), ('attendance_report', 'Attendance Report'), ('behavior_report', 'Behavior Report'), ('transcript', 'Academic Transcript'), ('class_performance', 'Class Performance'), ('parent_summary', 'Parent Summary'), ('custom', 'Custom Report')], db_index=True, max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Filters: academic_year, semester, date_range, etc.')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schools.classroom')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reportschedule')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='reports_rep_student_6f6467_idx'), models.Index(fields=['classroom', '-created_at'], name='reports_rep_classro_245aaf_idx'), models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx')],
            },
        ),
    ]
