# Generated by Django 6.0.1 on 2026-01-14 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name/class', max_length=50)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='resources.resourcecategory')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='schools.subject')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('file', 'File Upload'), ('link', 'External Link'), ('video', 'Video')], default='file', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/%d/')),
                ('external_link', models.URLField(blank=True, max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('access_level', models.CharField(choices=[('public', 'Public - All School'), ('classroom_only', 'Classroom Only'), ('specific_students', 'Specific Students'), ('teachers_only', 'Teachers Only')], db_index=True, default='public', max_length=30)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resources/thumbnails/%Y/%m/%d/')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='schools.classroom')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='schools.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Download',
                'verbose_name_plural': 'Resource Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category', '-created_at'], name='resources_r_categor_47f552_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='resources_r_uploade_f1a5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-download_count'], name='resources_r_downloa_2d221e_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['access_level', '-created_at'], name='resources_r_access__e9252c_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcedownload',
            index=models.Index(fields=['resource', '-downloaded_at'], name='resources_r_resourc_a48392_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcedownload',
            index=models.Index(fields=['user', '-downloaded_at'], name='resources_r_user_id_daba54_idx'),
        ),
    ]
