# Generated by Django 6.0.1 on 2026-01-14 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('academic', 'Academic'), ('attendance', 'Attendance'), ('behavior', 'Behavior'), ('participation', 'Participation'), ('custom', 'Custom')], max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='%', help_text='%, points, count, etc.', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
                ('tracked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('midterm', 'Mid-Term Report'), ('final', 'Final Report'), ('quarterly', 'Quarterly Report'), ('custom', 'Custom Report')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('report_period', models.CharField(help_text='e.g., Q1, Semester 1', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('overall_performance', models.TextField()),
                ('academic_summary', models.TextField()),
                ('attendance_summary', models.TextField(blank=True)),
                ('behavior_summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/progress/%Y/%m/')),
                ('shared_with_parent', models.BooleanField(default=False)),
                ('parent_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='schools.classroom')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Report',
                'verbose_name_plural': 'Progress Reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', '-generated_at'], name='performance_student_d5c119_idx'), models.Index(fields=['classroom', '-generated_at'], name='performance_classro_014939_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(help_text='e.g., 2025-2026', max_length=20)),
                ('semester', models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('full_year', 'Full Year')], default='full_year', max_length=20)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, help_text='A+, A, B+, etc.', max_length=2)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, help_text='Grade Point Average', max_digits=3)),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('behavior_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_passing', models.BooleanField(default=True)),
                ('is_honor_roll', models.BooleanField(default=False)),
                ('teacher_comments', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='schools.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Grade',
                'verbose_name_plural': 'Student Grades',
                'ordering': ['-academic_year', 'classroom', '-overall_percentage'],
                'indexes': [models.Index(fields=['student', '-academic_year'], name='performance_student_a52ada_idx'), models.Index(fields=['classroom', '-overall_percentage'], name='performance_classro_41bb80_idx')],
                'unique_together': {('student', 'classroom', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(default='full_year', max_length=20)),
                ('assignment_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quiz_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('letter_grade', models.CharField(blank=True, max_length=2)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('completed_assignments', models.PositiveIntegerField(default=0)),
                ('total_quizzes', models.PositiveIntegerField(default=0)),
                ('completed_quizzes', models.PositiveIntegerField(default=0)),
                ('is_improving', models.BooleanField(default=False)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='schools.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='schools.subject')),
            ],
            options={
                'verbose_name': 'Subject Performance',
                'verbose_name_plural': 'Subject Performances',
                'ordering': ['-academic_year', 'subject'],
                'indexes': [models.Index(fields=['student', 'subject', '-academic_year'], name='performance_student_348e18_idx')],
                'unique_together': {('student', 'subject', 'classroom', 'academic_year', 'semester')},
            },
        ),
    ]
