# Generated by Django 6.0.1 on 2026-01-14 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('assignment_created', 'New Assignment'), ('assignment_graded', 'Assignment Graded'), ('quiz_created', 'New Quiz'), ('quiz_graded', 'Quiz Graded'), ('new_message', 'New Message'), ('new_announcement', 'New Announcement'), ('attendance_marked', 'Attendance Marked'), ('absence_alert', 'Absence Alert'), ('behavior_incident', 'Behavior Incident'), ('behavior_note', 'Behavior Note'), ('grade_updated', 'Grade Updated'), ('progress_report', 'Progress Report Available'), ('xp_earned', 'XP Earned'), ('level_up', 'Level Up'), ('badge_earned', 'Badge Earned'), ('achievement_unlocked', 'Achievement Unlocked'), ('resource_shared', 'Resource Shared'), ('system_alert', 'System Alert'), ('reminder', 'Reminder')], max_length=30)),
                ('title_template', models.CharField(help_text='Use {variable} for placeholders', max_length=255)),
                ('message_template', models.TextField(help_text='Use {variable} for placeholders')),
                ('email_subject_template', models.CharField(blank=True, max_length=255)),
                ('email_body_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('assignment_created', 'New Assignment'), ('assignment_graded', 'Assignment Graded'), ('quiz_created', 'New Quiz'), ('quiz_graded', 'Quiz Graded'), ('new_message', 'New Message'), ('new_announcement', 'New Announcement'), ('attendance_marked', 'Attendance Marked'), ('absence_alert', 'Absence Alert'), ('behavior_incident', 'Behavior Incident'), ('behavior_note', 'Behavior Note'), ('grade_updated', 'Grade Updated'), ('progress_report', 'Progress Report Available'), ('xp_earned', 'XP Earned'), ('level_up', 'Level Up'), ('badge_earned', 'Badge Earned'), ('achievement_unlocked', 'Achievement Unlocked'), ('resource_shared', 'Resource Shared'), ('system_alert', 'System Alert'), ('reminder', 'Reminder')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Batch',
                'verbose_name_plural': 'Notification Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_in_app', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', max_length=20)),
                ('enable_push', models.BooleanField(default=False)),
                ('enable_sms', models.BooleanField(default=False)),
                ('notify_assignments', models.BooleanField(default=True)),
                ('notify_quizzes', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_announcements', models.BooleanField(default=True)),
                ('notify_attendance', models.BooleanField(default=True)),
                ('notify_behavior', models.BooleanField(default=True)),
                ('notify_grades', models.BooleanField(default=True)),
                ('notify_gamification', models.BooleanField(default=True)),
                ('notify_resources', models.BooleanField(default=True)),
                ('enable_quiet_hours', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='e.g., 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='e.g., 07:00', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('assignment_created', 'New Assignment'), ('assignment_graded', 'Assignment Graded'), ('quiz_created', 'New Quiz'), ('quiz_graded', 'Quiz Graded'), ('new_message', 'New Message'), ('new_announcement', 'New Announcement'), ('attendance_marked', 'Attendance Marked'), ('absence_alert', 'Absence Alert'), ('behavior_incident', 'Behavior Incident'), ('behavior_note', 'Behavior Note'), ('grade_updated', 'Grade Updated'), ('progress_report', 'Progress Report Available'), ('xp_earned', 'XP Earned'), ('level_up', 'Level Up'), ('badge_earned', 'Badge Earned'), ('achievement_unlocked', 'Achievement Unlocked'), ('resource_shared', 'Resource Shared'), ('system_alert', 'System Alert'), ('reminder', 'Reminder')], db_index=True, max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reference_type', models.CharField(blank=True, help_text='assignment, quiz, message, etc.', max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', '-sent_at'], name='notificatio_recipie_b23b38_idx'), models.Index(fields=['recipient', 'is_read', '-sent_at'], name='notificatio_recipie_077e99_idx'), models.Index(fields=['notification_type', '-sent_at'], name='notificatio_notific_14afde_idx')],
            },
        ),
    ]
